ALTER TABLE `leads`.`user_role_permissions` 
ADD COLUMN `active` TINYINT(1) NOT NULL DEFAULT 0 ,
ADD COLUMN `created_by` INT UNSIGNED NOT NULL,
ADD COLUMN `created_date` DATETIME NOT NULL,
ADD COLUMN `updated_by` INT UNSIGNED NOT NULL,
ADD COLUMN `updated_date` DATETIME NOT NULL,
ADD COLUMN `deleted_by` INT UNSIGNED NULL ,
ADD COLUMN `deleted_date` DATETIME NULL ,
ADD COLUMN `deleted` TINYINT NOT NULL DEFAULT 0;
